# Generated by Django 5.0.1 on 2026-01-27 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etapa",
                    models.IntegerField(
                        choices=[
                            (1, "Preparação"),
                            (2, "Identificação de Perigos"),
                            (3, "Avaliação de Riscos"),
                            (4, "Planejamento e Controle"),
                            (5, "Monitoramento e Revisão"),
                            (6, "Comunicação e Cultura"),
                        ]
                    ),
                ),
                ("item_texto", models.TextField()),
                ("item_ordem", models.IntegerField()),
                ("concluido", models.BooleanField(default=False)),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                ("responsavel", models.CharField(blank=True, max_length=255)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.campaign",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Etapa",
                "verbose_name_plural": "Checklists Etapas",
                "db_table": "actions_checklist_etapa",
                "ordering": ["etapa", "item_ordem"],
                "unique_together": {("empresa", "campaign", "etapa", "item_ordem")},
            },
        ),
        migrations.CreateModel(
            name="PlanoAcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nivel_risco", models.CharField(max_length=20)),
                ("descricao_risco", models.TextField()),
                ("acao_proposta", models.TextField()),
                ("responsavel", models.CharField(max_length=255)),
                ("prazo", models.DateField()),
                ("recursos_necessarios", models.TextField(blank=True)),
                ("indicadores", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.campaign",
                    ),
                ),
                (
                    "dimensao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.dimensao",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Ação",
                "verbose_name_plural": "Planos de Ação",
                "db_table": "actions_plano_acao",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("arquivo", models.FileField(upload_to="evidencias/%Y/%m/")),
                ("descricao", models.TextField(blank=True)),
                ("tipo", models.CharField(max_length=50)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.campaign",
                    ),
                ),
                (
                    "checklist_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="actions.checklistetapa",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.empresa",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plano_acao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="actions.planoacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidência",
                "verbose_name_plural": "Evidências",
                "db_table": "actions_evidencia",
                "ordering": ["-created_at"],
            },
        ),
    ]
