# Generated by Django 5.0.1 on 2026-02-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0004_add_rich_editor_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planoacao",
            name="conteudo_html",
            field=models.TextField(
                blank=True,
                help_text="HTML renderizado do plano de ação para exportação",
            ),
        ),
    ]
