# Generated by Django 5.0.1 on 2026-01-27 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structure", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("rh", "RH"),
                            ("lideranca", "Liderança"),
                        ],
                        max_length=15,
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20)),
                (
                    "empresas",
                    models.ManyToManyField(
                        blank=True, related_name="usuarios_rh", to="tenants.empresa"
                    ),
                ),
                (
                    "setores_permitidos",
                    models.ManyToManyField(blank=True, to="structure.setor"),
                ),
                (
                    "unidades_permitidas",
                    models.ManyToManyField(blank=True, to="structure.unidade"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
                "db_table": "accounts_user_profile",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("import_csv", "Importação CSV"),
                            ("disparo_email", "Disparo de E-mails"),
                            ("export_relatorio", "Exportação de Relatório"),
                            ("create_campaign", "Criação de Campanha"),
                            ("view_dashboard", "Visualização Dashboard"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenants.empresa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "db_table": "accounts_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_au_user_id_470480_idx",
                    ),
                    models.Index(
                        fields=["empresa", "acao"],
                        name="accounts_au_empresa_8edb94_idx",
                    ),
                ],
            },
        ),
    ]
