# Generated by Django 5.0.1 on 2026-01-30 18:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="artigo",
            new_name="articles_ar_publica_0fd748_idx",
            old_name="articles_ar_publicad_idx",
        ),
        migrations.RenameIndex(
            model_name="artigo",
            new_name="articles_ar_status_98ac3b_idx",
            old_name="articles_ar_status_cat_idx",
        ),
        migrations.RenameIndex(
            model_name="artigo",
            new_name="articles_ar_destaqu_b5df74_idx",
            old_name="articles_ar_destaque_status_idx",
        ),
        migrations.AlterField(
            model_name="artigo",
            name="conteudo",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="Conteúdo completo do artigo com formatação rica",
                verbose_name="Conteúdo",
            ),
        ),
    ]
