# Generated by Django 5.0.1 on 2026-01-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LGPDComplianceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("concluido", models.BooleanField(default=False)),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("ordem", models.IntegerField(default=0)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Conformidade LGPD",
                "verbose_name_plural": "Itens de Conformidade LGPD",
                "db_table": "core_lgpd_compliance_item",
                "ordering": ["ordem"],
                "unique_together": {("empresa", "ordem")},
            },
        ),
    ]
