# Generated by Django 5.0.1 on 2026-01-27 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimDimensaoHSE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Dimensão HSE",
                "verbose_name_plural": "Dimensões HSE",
                "db_table": "analytics_dim_dimensao_hse",
            },
        ),
        migrations.CreateModel(
            name="DimTempo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(unique=True)),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("trimestre", models.IntegerField()),
                ("semana_ano", models.IntegerField()),
                ("dia_semana", models.IntegerField()),
                ("nome_mes", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Dimensão Tempo",
                "verbose_name_plural": "Dimensões Tempo",
                "db_table": "analytics_dim_tempo",
            },
        ),
        migrations.CreateModel(
            name="DimDemografia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faixa_etaria", models.CharField(max_length=10)),
                ("tempo_empresa", models.CharField(max_length=10)),
                ("genero", models.CharField(max_length=1)),
            ],
            options={
                "verbose_name": "Dimensão Demografia",
                "verbose_name_plural": "Dimensões Demografia",
                "db_table": "analytics_dim_demografia",
                "unique_together": {("faixa_etaria", "tempo_empresa", "genero")},
            },
        ),
        migrations.CreateModel(
            name="DimEstrutura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa_id", models.IntegerField()),
                ("empresa_nome", models.CharField(max_length=255)),
                ("unidade_id", models.IntegerField()),
                ("unidade_nome", models.CharField(max_length=255)),
                ("setor_id", models.IntegerField()),
                ("setor_nome", models.CharField(max_length=255)),
                ("cargo_id", models.IntegerField()),
                ("cargo_nome", models.CharField(max_length=255)),
                ("cargo_nivel", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Dimensão Estrutura",
                "verbose_name_plural": "Dimensões Estrutura",
                "db_table": "analytics_dim_estrutura",
                "unique_together": {
                    ("empresa_id", "unidade_id", "setor_id", "cargo_id")
                },
            },
        ),
        migrations.CreateModel(
            name="FactIndicadorCampanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_convidados", models.IntegerField()),
                ("total_respondidos", models.IntegerField()),
                (
                    "percentual_adesao",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("total_risco_critico", models.IntegerField()),
                ("total_risco_importante", models.IntegerField()),
                ("total_risco_moderado", models.IntegerField()),
                ("total_risco_aceitavel", models.IntegerField()),
                (
                    "percentual_risco_alto",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("igrp_score", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.campaign",
                    ),
                ),
                (
                    "dim_estrutura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimestrutura",
                    ),
                ),
                (
                    "dim_tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimtempo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Indicador Campanha",
                "verbose_name_plural": "Fatos Indicadores Campanha",
                "db_table": "analytics_fact_indicador_campanha",
            },
        ),
        migrations.CreateModel(
            name="FactRespostaPergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qtd_valor_0", models.IntegerField(default=0)),
                ("qtd_valor_1", models.IntegerField(default=0)),
                ("qtd_valor_2", models.IntegerField(default=0)),
                ("qtd_valor_3", models.IntegerField(default=0)),
                ("qtd_valor_4", models.IntegerField(default=0)),
                ("media", models.DecimalField(decimal_places=2, max_digits=4)),
                ("total_respostas", models.IntegerField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.campaign",
                    ),
                ),
                (
                    "dim_estrutura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimestrutura",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.pergunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Resposta Pergunta",
                "verbose_name_plural": "Fatos Respostas Perguntas",
                "db_table": "analytics_fact_resposta_pergunta",
            },
        ),
        migrations.CreateModel(
            name="FactScoreDimensao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score_medio", models.DecimalField(decimal_places=2, max_digits=4)),
                ("probabilidade", models.IntegerField()),
                ("severidade", models.IntegerField()),
                ("nivel_risco", models.IntegerField()),
                ("classificacao", models.CharField(max_length=20)),
                ("cor", models.CharField(max_length=10)),
                ("total_respostas", models.IntegerField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.campaign",
                    ),
                ),
                (
                    "dim_demografia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimdemografia",
                    ),
                ),
                (
                    "dim_estrutura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimestrutura",
                    ),
                ),
                (
                    "dim_hse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimdimensaohse",
                    ),
                ),
                (
                    "dim_tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimtempo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Score Dimensão",
                "verbose_name_plural": "Fatos Score Dimensão",
                "db_table": "analytics_fact_score_dimensao",
                "indexes": [
                    models.Index(
                        fields=["campaign", "dim_estrutura"],
                        name="analytics_f_campaig_cf71b9_idx",
                    ),
                    models.Index(
                        fields=["campaign", "dim_hse"],
                        name="analytics_f_campaig_71f086_idx",
                    ),
                    models.Index(
                        fields=["campaign", "classificacao"],
                        name="analytics_f_campaig_144afd_idx",
                    ),
                ],
            },
        ),
    ]
