# Generated by Django 5.0.1 on 2026-02-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_add_sector_analysis_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sectoranalysis",
            new_name="analytics_s_empresa_93b4f0_idx",
            old_name="analytics_s_empresa_idx",
        ),
        migrations.RenameIndex(
            model_name="sectoranalysis",
            new_name="analytics_s_setor_i_6affdf_idx",
            old_name="analytics_s_setor_c_idx",
        ),
        migrations.RenameIndex(
            model_name="sectoranalysis",
            new_name="analytics_s_status_830252_idx",
            old_name="analytics_s_status_idx",
        ),
        migrations.AlterField(
            model_name="sectoranalysis",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sectoranalysis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
