# Generated by Django 5.0.1 on 2026-01-27 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimensao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("negativo", "Negativo"), ("positivo", "Positivo")],
                        max_length=10,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("ordem", models.IntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Dimensão",
                "verbose_name_plural": "Dimensões",
                "db_table": "surveys_dimensao",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("active", "Ativa"),
                            ("closed", "Encerrada"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="tenants.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campanha",
                "verbose_name_plural": "Campanhas",
                "db_table": "surveys_campaign",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.IntegerField()),
                ("texto", models.TextField()),
                ("texto_ajuda", models.TextField(blank=True)),
                ("ordem", models.IntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "dimensao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perguntas",
                        to="surveys.dimensao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pergunta",
                "verbose_name_plural": "Perguntas",
                "db_table": "surveys_pergunta",
                "ordering": ["numero"],
                "unique_together": {("dimensao", "numero")},
            },
        ),
    ]
