# Generated by Django 5.0.1 on 2026-01-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("total_funcionarios", models.IntegerField(default=0)),
                ("logo_url", models.URLField(blank=True)),
                ("favicon_url", models.URLField(blank=True)),
                ("cor_primaria", models.CharField(default="#0d6efd", max_length=7)),
                ("cor_secundaria", models.CharField(default="#6c757d", max_length=7)),
                (
                    "nome_app",
                    models.CharField(default="VIVAMENTE 360º", max_length=100),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "tenants_empresa",
                "ordering": ["nome"],
            },
        ),
    ]
