# Generated by Django 5.0.1 on 2026-01-27 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structure", "0001_initial"),
        ("surveys", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hash_token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("email_encrypted", models.TextField()),
                ("nome_encrypted", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviado"),
                            ("used", "Utilizado"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.campaign",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.cargo",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.empresa",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.setor",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convite",
                "verbose_name_plural": "Convites",
                "db_table": "invitations_survey_invitation",
                "indexes": [
                    models.Index(
                        fields=["hash_token"], name="invitations_hash_to_d0ce4a_idx"
                    ),
                    models.Index(
                        fields=["campaign", "status"],
                        name="invitations_campaig_a3c9b8_idx",
                    ),
                ],
            },
        ),
    ]
