# Generated by Django 5.0.1 on 2026-01-27 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structure", "0001_initial"),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faixa_etaria",
                    models.CharField(
                        choices=[
                            ("18-24", "18 a 24 anos"),
                            ("25-34", "25 a 34 anos"),
                            ("35-49", "35 a 49 anos"),
                            ("50-59", "50 a 59 anos"),
                            ("60+", "60 anos ou mais"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tempo_empresa",
                    models.CharField(
                        choices=[
                            ("0-1", "Menos de 1 ano"),
                            ("1-3", "1 a 3 anos"),
                            ("3-5", "3 a 5 anos"),
                            ("5-10", "5 a 10 anos"),
                            ("10+", "Mais de 10 anos"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("O", "Outro"),
                            ("N", "Prefiro não informar"),
                        ],
                        max_length=1,
                    ),
                ),
                ("respostas", models.JSONField()),
                ("lgpd_aceito", models.BooleanField(default=False)),
                ("lgpd_aceito_em", models.DateTimeField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="surveys.campaign",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.cargo",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.setor",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta",
                "verbose_name_plural": "Respostas",
                "db_table": "responses_survey_response",
                "indexes": [
                    models.Index(
                        fields=["campaign", "created_at"],
                        name="responses_s_campaig_ad5f50_idx",
                    ),
                    models.Index(
                        fields=["campaign", "unidade"],
                        name="responses_s_campaig_994b08_idx",
                    ),
                    models.Index(
                        fields=["campaign", "setor"],
                        name="responses_s_campaig_cf1b35_idx",
                    ),
                ],
            },
        ),
    ]
