# Generated by Claude on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="comentario_livre",
            field=models.TextField(
                blank=True,
                help_text="Comentário opcional do colaborador"
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="sentimento_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="-1.0 (muito negativo) a 1.0 (muito positivo)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="sentimento_categorias",
            field=models.JSONField(
                blank=True,
                help_text="Categorias e análise identificada pela IA",
                null=True,
            ),
        ),
    ]
